name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-bazel:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    steps:
      - run: rm $(which bazel)
        if: matrix.os != 'windows'
      - run: Remove-Item -Path (Get-Command bazel.exe).Source
        if: matrix.os == 'windows'
      - uses: actions/checkout@v4
      - uses: ./
        with:
          bazelisk-cache: true
          bazelisk-version: 1.x
          remote-cache: true
          repository-cache: true
      - uses: actions/checkout@v4
        with:
          repository: bazelbuild/examples
          path: examples
      - run: bazel build --announce_rc :ProjectRunner
        working-directory: examples/java-tutorial
      - if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3
